WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/users.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models;

public class users
{
    [Key] public double Id { get; set; }

    [Required]
    [StringLength(60, MinimumLength = 3)]
    [Display(Name = "User Name")]
    public String name { get; set; }

    [Display(Name = "User password")]
    [DataType(DataType.Password)]
    public String password { get; set; }

    public string phone_num { get; set; }
    [DataType(DataType.EmailAddress)] public string email { get; set; }

    [MaxLength(7)] public String? gender { get; set; }

    [Display(Name = "Date Of Brith")]
    [DataType(DataType.Date)]
    public DateTime? dateOfBrith { get; set; }
    
    //[RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$"), StringLength(5)]
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers;

public class MovieController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View("testing2");
    }
    public IActionResult welcome(string name, int ID = 3)
    {
        ViewData["Message"] = "Hello " + name;
        ViewData["NumTimes"] = ID;

        return View("testing2");

    }
}

WebApplication1/Controllers/testingController.cs
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers;

public class testingController : Controller
{
    // GET
    
    
    public IActionResult Index()
    {
        return View("testing");
    }

    public String hello()
    {
        return "pubplic method that return a string ";
    }

    public String parameter(String name, double id)
    {
        //Uses HtmlEncoder.Default.Encode to protect the app from malicious input, such as through JavaScript.
        return HtmlEncoder.Default.Encode($"my name is: {name} and my id number is : {id}");

        //return ($"my name is: {name} and my id number is : {id}");
        //the url is
        //https://localhost:7134/testing/parameter?name=Qossay&id=1180235
    }
    public string parameter2(string name, int ID = 3)
    {
        //Console.WriteLine(DateTime.Now - TimeSpan.FromDays(7));
        return HtmlEncoder.Default.Encode($"Hello {name}, ID: {ID}");
        
    }
    
}

WebApplication1/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class userController : Controller
    {
        private readonly WebApplication1Context _context;
        
        // dependency injection
        public userController(WebApplication1Context context)
        {
            _context = context;
        }

        // GET: user
        // public async Task<IActionResult> Index()
        // {
        //       return _context.users != null ? 
        //                   View(await _context.users.ToListAsync()) :
        //                   Problem("Entity set 'WebApplication1Context.users'  is null.");
        // }
        
        //https://localhost:7134/user?name=Ghos
        [HttpGet]
        public async Task<IActionResult> Index(string? name , string? email)
        {
            var user = from VAR in _context.users
                select VAR;
            if (!string.IsNullOrEmpty(name))
            {
                user = user.Where(s => s.name!.Contains(name));
            }

            if (!string.IsNullOrEmpty(email))
            {
                user = user.Where(s => s.email!.Contains(email));

            }

            return View(await user.ToListAsync());
        }

        // GET: user/Details/5
        public async Task<IActionResult> Details(double? id)
        {
            if (id == null || _context.users == null)
            {
                return NotFound();
            }

            var users = await _context.users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // GET: user/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: user/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,password,email,gender,phone_num,dateOfBrith")] users users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(users);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: user/Edit/5
        public async Task<IActionResult> Edit(double? id)
        {
            if (id == null || _context.users == null)
            {
                return NotFound();
            }

            var users = await _context.users.FindAsync(id);
            if (users == null)
            {
                return NotFound();
            }
            return View(users);
        }

        // POST: user/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(double id, [Bind("Id,name,password,email,gender,phone_num,dateOfBrith")] users users)
        {
            if (id != users.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!usersExists(users.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: user/Delete/5
        public async Task<IActionResult> Delete(double? id)
        {
            if (id == null || _context.users == null)
            {
                return NotFound();
            }

            var users = await _context.users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // POST: user/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(double id)
        {
            if (_context.users == null)
            {
                return Problem("Entity set 'WebApplication1Context.users'  is null.");
            }
            var users = await _context.users.FindAsync(id);
            if (users != null)
            {
                _context.users.Remove(users);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool usersExists(double id)
        {
          return (_context.users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "My First .netPage";
}

<div class="text-center">
    <h1 class="display-4">Welcome LOL </h1>
    <p>My facbook acount <a  href="https://www.facebook.com/qossay.zeineddin">Facbook</a>.</p>
</div>

WebApplication1/Views/Movie/testing2.cshtml
@{
    ViewData["Title"] = "hello";
}

<div>
    <h2>
        Hello lool
    </h2>
    
<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]!; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Qossay</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="testing" asp-action="Index">testing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">testing2</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="user" asp-action="Index">users</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/testing/testing.cshtml
@{
    ViewData["Title"] = "my view";
}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/img.css"/>
</head>
    <body>
        <h2>The first View</h2>
        <p>Hello from my new viwe Template!</p>
        <div class="box">
            <span>
                <img class="img" src="img/img1.jpg" alt="my">
            </span>
            <span>
                <video class="mp4" controls>
                    <source src="video/video1.mp4" type="video/mp4"/>
                </video>
            </span>
        </div>
        <div >
            <h4 style="margin-bottom: 30px;">
                A view template file name wasn't specified, so MVC defaulted to using the default view file.
                When the view file name isn't specified, the default view is returned. The default view has the
                same name as the action method, Index in this example. The view template /Views/HelloWorld/Index.cshtml is used.
                
            </h4>
        </div>
    </body>
</html>

WebApplication1/Views/user/Create.cshtml
@model WebApplication1.Models.users

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>users</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control"/>
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control"/>
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control"/>
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control"/>
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone_num" class="control-label"></label>
                <input asp-for="phone_num" class="form-control"/>
                <span asp-validation-for="phone_num" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dateOfBrith" class="control-label"></label>
                <input asp-for="dateOfBrith" class="form-control"/>
                <span asp-validation-for="dateOfBrith" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebApplication1/Views/user/Delete.cshtml
@model WebApplication1.Models.users

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>users</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.phone_num)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.phone_num)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dateOfBrith)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dateOfBrith)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/Views/user/Details.cshtml
@model WebApplication1.Models.users

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>users</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.phone_num)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.phone_num)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dateOfBrith)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dateOfBrith)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/user/Edit.cshtml
@model WebApplication1.Models.users

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>users</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control"/>
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control"/>
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control"/>
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control"/>
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone_num" class="control-label"></label>
                <input asp-for="phone_num" class="form-control"/>
                <span asp-validation-for="phone_num" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dateOfBrith" class="control-label"></label>
                <input asp-for="dateOfBrith" class="form-control"/>
                <span asp-validation-for="dateOfBrith" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebApplication1/Views/user/Index.cshtml
@model IEnumerable<WebApplication1.Models.users>

@{
    ViewData["Title"] = "data testing";
}

<head>
    <link rel="stylesheet" href="css/site.css"/>
</head>
<h1 class="index">Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="user" asp-action="Index" method="get">
    <p>
        Search for user by his name : <input type="text" name="name"/>
        <input type="submit" value="Filter"/>
    </p>
</form>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone_num)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateOfBrith)
        </th>
        <th>
            userAPI
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone_num)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateOfBrith)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>